using Futurum.Microsoft.Extensions.DependencyInjection.Generator.Core;

namespace Futurum.Microsoft.Extensions.DependencyInjection.Generator;

public static class WrapperSourceGeneratorWriter
{
    public static string Write(string className, string methodName, Action<IndentedStringBuilder> writer, bool isNotMainMethod, bool skipVersion = false)
    {
        var codeBuilder = new IndentedStringBuilder();
        codeBuilder
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        codeBuilder
            .AppendLine("namespace Microsoft.Extensions.DependencyInjection")
            .AppendLine("{")
            .IncrementIndent();

        if (!isNotMainMethod)
        {
            if (!skipVersion)
            {
                codeBuilder
                    .Append("[global::System.CodeDom.Compiler.GeneratedCode(\"")
                    .Append(ThisAssembly.Project.AssemblyName)
                    .Append("\", \"")
                    .Append(ThisAssembly.Info.Version)
                    .AppendLine("\")]");
            }

            codeBuilder
                .AppendLine("[global::System.Diagnostics.DebuggerNonUserCodeAttribute]")
                .AppendLine("[global::System.Diagnostics.DebuggerStepThroughAttribute]");
        }

        codeBuilder
            .AppendLine($"public static partial class {className}FuturumMicrosoftExtensionsDependencyInjectionExtensions")
            .AppendLine("{")
            .IncrementIndent();

        if (!isNotMainMethod)
        {
            codeBuilder
                .Append("public");
        }

        if (isNotMainMethod)
        {
            codeBuilder
                .Append("private");
        }

        codeBuilder
            .Append(" static global::Microsoft.Extensions.DependencyInjection.IServiceCollection")
            .Append(" ")
            .Append(methodName)
            .AppendLine("(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection serviceCollection)")
            .AppendLine("{")
            .IncrementIndent();

        writer(codeBuilder);

        codeBuilder
            .AppendLine("return serviceCollection;")
            .DecrementIndent()
            .AppendLine("}") // method
            .DecrementIndent()
            .AppendLine("}") // class
            .DecrementIndent()
            .AppendLine("}"); // namespace

        return codeBuilder.ToString();
    }
}